export class TabPlayer{
  constructor(onStep,onDone,onFrame=()=>{}){this.onStep=onStep;this.onDone=onDone;this.onFrame=onFrame;this.frame=0;this.events=[];this.eventStarts=[];this.eventDurations=[];this.totalBeats=0;this.index=-1;this.bpm=80;this.positionBeats=0;this.lastTimestamp=null;this.running=false;this.completed=false;this.tick=this.tick.bind(this)}
  start(events,bpm,from=0){this.stop();this.events=events;this.bpm=bpm;const starts=events.map((event,i)=>Number.isFinite(event.timeBeats)?event.timeBeats:i?events[i-1].timeBeats+(event.column-events[i-1].column)/4:0);const gaps=events.slice(1).map((event,i)=>Math.max(.25,starts[i+1]-starts[i]));const sorted=[...gaps].sort((a,b)=>a-b);const tailDuration=events.at(-1)?.durationBeats||(sorted.length?sorted[Math.floor(sorted.length/2)]:1);this.eventStarts=starts;this.eventDurations=[...gaps,tailDuration];this.totalBeats=(starts.at(-1)||0)+tailDuration;this.positionBeats=this.eventStarts[Math.min(Math.max(0,from),Math.max(0,events.length-1))]||0;this.index=-1;this.lastTimestamp=null;this.completed=false;this.resume()}
  resume(){if(this.running||this.completed)return;this.running=true;this.lastTimestamp=null;this.frame=requestAnimationFrame(this.tick)}
  tick(timestamp){if(!this.running)return;if(this.lastTimestamp!==null)this.positionBeats+=(timestamp-this.lastTimestamp)*this.bpm/60000;this.lastTimestamp=timestamp;const total=this.events.length;if(!total||this.positionBeats>=this.totalBeats){this.positionBeats=this.totalBeats;this.onFrame(this.positionBeats,total,0,1);this.running=false;this.frame=0;if(!this.completed){this.completed=true;this.onDone?.()}return}let current=0;while(current+1<total&&this.eventStarts[current+1]<=this.positionBeats)current++;if(current!==this.index){this.index=current;this.onStep?.(current,this.events[current])}const duration=this.eventDurations[current]||1,fraction=Math.max(0,Math.min(1,(this.positionBeats-this.eventStarts[current])/duration));this.onFrame(this.positionBeats,current,fraction,this.positionBeats/this.totalBeats);this.frame=requestAnimationFrame(this.tick)}
  pause(){if(!this.running)return;this.running=false;cancelAnimationFrame(this.frame);this.frame=0;this.lastTimestamp=null}
  stop(){this.pause();this.positionBeats=0;this.index=-1;this.completed=false}
  setTempo(bpm){this.bpm=bpm}
}
