const key='tabu-progress-v1';
const fresh=()=>({xp:0,minutes:0,seconds:0,correct:0,attempts:0,streak:0,lastDate:'',sessions:[],completed:[],goalDate:'',goalMinutes:0,goalAwardDate:''});
export const state={route:'practice',exerciseId:'fikrimin-ince-gulu',bpm:72,mode:'Takip',running:false,step:0,seconds:0,metronome:false,loop:false,slow:100,noteDisplay:localStorage.getItem('tabu-note-display')||'fret',progress:load(),editorText:'e|--0---1---3---1---0--|\nB|---------------------|\nG|---------------------|\nD|---------------------|\nA|---------------------|\nE|---------------------|'};
function load(){try{return {...fresh(),...JSON.parse(localStorage.getItem(key)||'{}')}}catch{return fresh()}}
export function save(){localStorage.setItem(key,JSON.stringify(state.progress))}
export function addXP(n){state.progress.xp+=n;save()}
export function recordSession(title,durationSeconds=60){const p=state.progress;const today=new Date().toISOString().slice(0,10);p.seconds=(p.seconds||p.minutes*60)+durationSeconds;p.minutes=Math.floor(p.seconds/60);const priorGoalSeconds=p.goalDate===today?(p.goalSeconds||p.goalMinutes*60):0;p.goalSeconds=priorGoalSeconds+durationSeconds;p.goalDate=today;p.goalMinutes=Math.floor(p.goalSeconds/60);if(p.lastDate!==today){const yesterday=new Date(Date.now()-86400000).toISOString().slice(0,10);p.streak=p.lastDate===yesterday?p.streak+1:1;p.lastDate=today}p.sessions.unshift({title,date:today,minutes:Math.max(1,Math.ceil(durationSeconds/60))});p.sessions=p.sessions.slice(0,8);const goalReached=p.goalSeconds>=600&&p.goalAwardDate!==today;if(goalReached){p.goalAwardDate=today;p.xp+=100}save();return goalReached}
export function recordAnswer(correct,exerciseId=null){const p=state.progress;p.attempts++;if(correct){p.correct++;p.xp+=10}if(exerciseId){p.exercises||={};const item=p.exercises[exerciseId]||{correct:0,wrong:0,completions:0,highestBpm:0,bestAccuracy:0,seconds:0};item[correct?'correct':'wrong']++;item.highestBpm=Math.max(item.highestBpm,state.bpm);p.exercises[exerciseId]=item}save()}
export function completeExercise(title,exerciseId=null,summary={}){const p=state.progress;p.completed=[...new Set([...p.completed,title])];if(exerciseId){p.exercises||={};const item=p.exercises[exerciseId]||{correct:0,wrong:0,completions:0,highestBpm:0,bestAccuracy:0,seconds:0};item.completions++;item.highestBpm=Math.max(item.highestBpm,state.bpm);item.seconds+=summary.seconds||0;item.bestAccuracy=Math.max(item.bestAccuracy,summary.accuracy||0);p.exercises[exerciseId]=item}p.xp+=50;save()}
